// ---------- Mushaf: the Quran with its English translation, recitation, bookmarks and a daily wird ----------
// Texts are generated by tools/build_quran.py (Tanzil, via api.alquran.cloud) into quran/*.json
// and fetched on first use; js/quran-meta.js holds the surah list and the page / juz starts.
(() => {
  'use strict';
  const { T, I, $, el, button, load, store, dayKey, toast, onRemote } = window.noonUI;
  const M = window.NOON_QURAN_META;
  const KEY = 'noon-sweep-quran';
  const root = $('view-quran');
  const TOTAL = 6236, PAGES = 604;
  const AR = '٠١٢٣٤٥٦٧٨٩';
  const ar = (n) => String(n).replace(/[0-9]/g, (d) => AR[d]); // Mushaf numbers are always Arabic-Indic
  const RECITERS = [
    ['ar.alafasy', 128, 'مشاري العفاسي', 'Mishary Alafasy'],
    ['ar.husary', 128, 'محمود خليل الحصري', 'Mahmoud Khalil Al-Husary'],
    ['ar.minshawi', 128, 'محمد صديق المنشاوي', 'Mohamed Siddiq El-Minshawi'],
    ['ar.abdulbasitmurattal', 64, 'عبد الباسط عبد الصمد', 'Abdul Basit Abdus Samad'],
    ['ar.abdurrahmaansudais', 192, 'عبد الرحمن السديس', 'Abdurrahman As-Sudais'],
    ['ar.mahermuaiqly', 128, 'ماهر المعيقلي', 'Maher Al-Muaiqly'],
    ['ar.hudhaify', 128, 'علي الحذيفي', 'Ali Al-Hudhaify'],
    ['ar.husarymujawwad', 128, 'الحصري (مجوّد)', 'Al-Husary (mujawwad)'],
    // The teaching recitation: slow and clear, for those learning to read (everyayah.com).
    ['muallim', 0, 'الحصري المعلّم (للتعليم)', 'Al-Husary, teaching recitation',
      (i) => `https://everyayah.com/data/Husary_Muallim_128kbps/${String(surahOf(i) + 1).padStart(3, '0')}${String(ayahOf(i)).padStart(3, '0')}.mp3`]
  ];
  // Tafsirs: the recognised ones, fetched per verse (alquran.cloud, or spa5k/tafsir_api on jsDelivr).
  const TAFSIRS = [
    ['muyassar', 'التفسير الميسّر (مجمع الملك فهد)', 'Al-Muyassar (King Fahd Complex)', 'alq', 'ar.muyassar'],
    ['saddi', 'تفسير السعدي', 'Tafsir as-Sa‘di', 'cdn', 'ar-tafseer-al-saddi'],
    ['ibnkathir', 'تفسير ابن كثير', 'Tafsir Ibn Kathir', 'cdn', 'ar-tafsir-ibn-kathir'],
    ['tabari', 'تفسير الطبري', 'Tafsir at-Tabari', 'cdn', 'ar-tafsir-al-tabari'],
    ['qurtubi', 'تفسير القرطبي', 'Tafsir al-Qurtubi', 'alq', 'ar.qurtubi'],
    ['baghawi', 'تفسير البغوي', 'Tafsir al-Baghawi', 'cdn', 'ar-tafsir-al-baghawi'],
    ['wasit', 'التفسير الوسيط (طنطاوي)', 'Al-Wasit (Tantawi)', 'cdn', 'ar-tafsir-al-wasit'],
    ['jalalayn', 'تفسير الجلالين', 'Tafsir al-Jalalayn', 'alq', 'ar.jalalayn'],
    ['en-ibnkathir', 'ابن كثير المختصر (بالإنجليزية)', 'Ibn Kathir, abridged (English)', 'cdn', 'en-tafisr-ibn-kathir']
  ];
  // Translations: English is kept with the app; the others are read per surah from alquran.cloud.
  const TRANS = [
    ['en', 'English — Sahih International'], ['ur.jalandhry', 'اردو — جالندھری'], ['id.indonesian', 'Bahasa Indonesia'],
    ['fr.hamidullah', 'Français — Hamidullah'], ['tr.diyanet', 'Türkçe — Diyanet'], ['ms.basmeih', 'Bahasa Melayu — Basmeih'],
    ['bn.bengali', 'বাংলা — Muhiuddin Khan'], ['es.cortes', 'Español — Cortés'], ['de.aburida', 'Deutsch — Abu Rida'], ['ru.kuliev', 'Русский — Кулиев']
  ];
  const transCache = {};
  const transLang = () => (TRANS.some((t) => t[0] === S.transLang) ? S.transLang : 'en');
  function transText(s, i) {
    if (transLang() === 'en') return txt.en ? txt.en[i] : '';
    const c = transCache[`${transLang()}:${s}`];
    return c ? c[i - starts[s]] : '';
  }
  // Tajweed colours: [code, Arabic name, English name]
  const TAJWEED = [
    ['h', 'همزة وصل ولام وحروف لا تُنطق', 'Hamzat al-wasl, silent letters'], ['n', 'مدّ طبيعي (حركتان)', 'Natural madd (2)'],
    ['p', 'مدّ جائز (٢، ٤، ٦)', 'Permissible madd (2, 4, 6)'], ['o', 'مدّ واجب (٤–٥)', 'Obligatory madd (4–5)'],
    ['m', 'مدّ لازم (٦ حركات)', 'Necessary madd (6)'], ['q', 'قلقلة', 'Qalqalah'], ['g', 'غنّة', 'Ghunnah'],
    ['f', 'إخفاء', 'Ikhfa'], ['c', 'إخفاء شفوي', 'Ikhfa shafawi'], ['i', 'إقلاب', 'Iqlab'],
    ['a', 'إدغام بغنّة', 'Idgham with ghunnah'], ['u', 'إدغام بلا غنّة', 'Idgham without ghunnah'],
    ['w', 'إدغام شفوي', 'Idgham shafawi'], ['d', 'إدغام متجانسين أو متقاربين', 'Idgham (similar letters)']
  ];

  // ---- saved state ----
  const blank = () => ({
    last: null, marks: [], goal: 5, today: { day: dayKey(), pages: [] },
    khatma: { pages: [], count: 0 }, font: 30, trans: I.isEn, reciter: 'ar.alafasy', theme: 'paper',
    tajweed: false, tajRules: false, repeat: 1, gap: 0, rate: 1, hide: false, tafsir: I.isEn ? 'en-ibnkathir' : 'muyassar', inlineTafsir: false
  });
  let S = Object.assign(blank(), load(KEY, {}));
  // Today's goal: fixed, or worked out from a completion date (pages left ÷ days left).
  const planDays = () => {
    if (!S.planEnd) return 0;
    const [y, m, d] = S.planEnd.split('-').map(Number);
    return Math.round((new Date(y, m - 1, d) - new Date(new Date().toDateString())) / 864e5) + 1;
  };
  function goal() {
    const days = planDays();
    if (days < 1) return S.goal; // no plan, or its date has passed
    const left = PAGES - S.khatma.pages.length + S.today.pages.length; // today's pages still count toward today
    return Math.max(1, Math.ceil(left / days));
  }
  const fresh = () => { if (!S.today || S.today.day !== dayKey()) S.today = { day: dayKey(), pages: [] }; };
  const save = () => { S.updatedAt = Date.now(); store(KEY, S); };
  fresh();

  // ---- verse arithmetic (global index 0..6235) ----
  const starts = [];
  M.surahs.reduce((a, s) => { starts.push(a); return a + s[4]; }, 0);
  function bsearch(arr, i) { let lo = 0, hi = arr.length - 1; while (lo < hi) { const mid = (lo + hi + 1) >> 1; if (arr[mid] <= i) lo = mid; else hi = mid - 1; } return lo; }
  const surahOf = (i) => bsearch(starts, i);             // 0-based surah
  const pageOf = (i) => bsearch(M.pages, i) + 1;         // 1-based page
  const juzOf = (i) => bsearch(M.juz, i) + 1;
  const ayahOf = (i) => i - starts[surahOf(i)] + 1;
  const surahName = (s) => (I.isEn ? M.surahs[s][1] : M.surahs[s][0].replace(/^سُورَةُ\s*/, ''));
  const refText = (i) => `${surahName(surahOf(i))} ${I.num(ayahOf(i))}`;
  const sajda = new Set(M.sajdas);

  // ---- texts, fetched once ----
  const files = {}, txt = {}; // pending fetches, loaded arrays
  function data(name) {
    if (!files[name]) {
      files[name] = fetch(`quran/${name}.json`).then((r) => { if (!r.ok) throw new Error(r.status); return r.json(); })
        .then((v) => (txt[name] = v));
      files[name].catch(() => { delete files[name]; });
    }
    return files[name];
  }
  const fontReady = () => (document.fonts && document.fonts.load ? document.fonts.load('30px "Amiri Quran"', 'بِسْمِ').catch(() => {}) : Promise.resolve());

  // ---- search ----
  const MARKS = /[ؐ-ًؚ-ٰٟۖ-ۭـ]/g;
  const norm = (s) => s.replace(MARKS, '').replace(/[أإآٱ]/g, 'ا').replace(/ى/g, 'ي').replace(/ة/g, 'ه')
    .replace(/ؤ/g, 'و').replace(/ئ/g, 'ي').replace(/\s+/g, ' ').trim();
  let normCache = null;
  async function search(q) {
    const latin = q.replace(/[٠-٩]/g, (d) => AR.indexOf(d));
    // "2:255" or "2 255" jumps to a verse; a bare number up to 604 opens that page.
    let m = /^(\d{1,3})\s*[:：\s]\s*(\d{1,3})$/.exec(latin.trim());
    if (m) {
      const s = Number(m[1]) - 1, a = Number(m[2]);
      if (s >= 0 && s < 114 && a >= 1 && a <= M.surahs[s][4]) return { jump: starts[s] + a - 1 };
    }
    m = /^(\d{1,3})$/.exec(latin.trim());
    if (m && Number(m[1]) >= 1 && Number(m[1]) <= PAGES) return { page: Number(m[1]) };
    const results = [];
    if (/[a-z]/i.test(q)) {
      const en = await data('en'), needle = q.toLowerCase();
      for (let i = 0; i < TOTAL && results.length < 60; i++) if (en[i].toLowerCase().includes(needle)) results.push(i);
    } else {
      if (!normCache) normCache = (await data('clean')).map(norm);
      const needle = norm(q);
      if (needle.length < 2) return { results };
      for (let i = 0; i < TOTAL && results.length < 60; i++) if (normCache[i].includes(needle)) results.push(i);
    }
    return { results };
  }

  // ---- reading progress ----
  function markPage(p) {
    fresh();
    let changed = false;
    if (!S.today.pages.includes(p)) { S.today.pages.push(p); changed = true; }
    if (!S.khatma.pages.includes(p)) {
      S.khatma.pages.push(p); changed = true;
      if (S.khatma.pages.length >= PAGES) {
        S.khatma = { pages: [], count: (S.khatma.count || 0) + 1 };
        toast(T('مبارك! أتممت ختمة القرآن الكريم. تقبّل الله منك.'));
      }
    }
    if (!changed) return;
    (S.log = S.log || {})[S.today.day] = S.today.pages.length; // pages per day, for the report
    save();
    window.dispatchEvent(new CustomEvent('noon-habit', { detail: { id: 'quran', value: S.today.pages.length } }));
    if (S.today.pages.length === goal()) toast(T('أتممت وردك اليومي من القرآن. بارك الله فيك.'));
    if (!root.hidden) renderIndex();
  }
  function setLast(i) {
    if (S.last && S.last.i === i) return;
    S.last = { i, at: Date.now() };
    save();
  }
  const isMarked = (i) => S.marks.some((b) => b.i === i);
  function toggleMark(i) {
    if (isMarked(i)) S.marks = S.marks.filter((b) => b.i !== i);
    else S.marks.unshift({ i, at: Date.now() });
    save();
  }

  // ================= the index (in the tab) =================
  let tab = 'surahs', query = '', found = null;
  function renderIndex() {
    fresh();
    root.replaceChildren();
    const head = el('div', 'view-head');
    head.append(el('h2', '', T('المصحف الشريف')), el('span', 'view-sub', `${I.num(114)} ${T('سورة')} · ${I.num(PAGES)} ${I.tp('count', 'صفحة')}`));
    root.append(head);

    // Continue + today's wird.
    // The verse of the day (same choice as the morning reminder in js/sunnah.js).
    const VS = window.NOON_EXTRAS && window.NOON_EXTRAS.verses;
    const now = new Date();
    const V = VS && VS[Math.floor(new Date(now.getFullYear(), now.getMonth(), now.getDate()).getTime() / 864e5) % VS.length];
    if (V) {
      const vd = el('div', 'daily-card');
      const t = el('p', 'daily-text is-quran', V.ar); t.lang = 'ar'; t.dir = 'rtl';
      vd.append(el('span', 'q-kicker', T('آية اليوم')), t);
      if (I.isEn || S.trans) { const e = el('p', 'daily-en', V.en); e.dir = 'ltr'; vd.append(e); }
      const acts = el('div', 'hadith-acts');
      acts.append(el('span', 'hint', I.isEn ? V.refEn : V.refAr), button('link-btn', T('افتح في المصحف'), () => open(V.i)),
        button('link-btn', T('مشاركة ككارت'), () => window.noonCard && window.noonCard.shareImage({ kicker: T('آية اليوم'), title: I.isEn ? V.refEn : V.refAr, body: V.ar, quran: true })));
      vd.append(acts);
      root.append(vd);
    }
    const top = el('div', 'q-top');
    const cont = el('div', 'q-card q-continue');
    if (S.last) {
      const i = S.last.i;
      cont.append(el('span', 'q-kicker', T('تابع القراءة')), el('b', 'q-big', refText(i)),
        el('span', 'q-meta', `${T('الجزء')} ${I.num(juzOf(i))} · ${T('صفحة')} ${I.num(pageOf(i))}`),
        button('btn btn-primary', T('متابعة'), () => open(i)));
    } else {
      cont.append(el('span', 'q-kicker', T('ابدأ القراءة')), el('b', 'q-big', I.isEn ? 'Al-Fatiha' : 'الفاتحة'),
        el('span', 'q-meta', T('من أول المصحف')), button('btn btn-primary', T('ابدأ'), () => open(0)));
    }
    const wird = el('div', 'q-card q-wird');
    const done = S.today.pages.length;
    const g = goal();
    const bar = el('div', 'q-bar'); const fill = el('span'); fill.style.width = `${Math.min(100, (done / g) * 100)}%`; bar.append(fill);
    const goalSel = el('select', 'q-goal');
    goalSel.setAttribute('aria-label', T('الورد اليومي'));
    [[1, '١ صفحة'], [2, '٢ صفحتان'], [4, '٤ صفحات'], [5, '٥ صفحات'], [10, '١٠ صفحات'], [20, '٢٠ صفحة (جزء)'], [40, '٤٠ صفحة (جزءان)']]
      .forEach(([v, label]) => goalSel.append(new Option(T(label), String(v))));
    goalSel.value = String(S.goal);
    goalSel.addEventListener('change', () => { S.goal = Number(goalSel.value) || 5; save(); renderIndex(); });
    // A completion plan: finish the Mushaf by a chosen date.
    const plan = el('label', 'q-plan');
    const endIn = el('input'); endIn.type = 'date'; endIn.value = S.planEnd || '';
    endIn.min = dayKey();
    endIn.addEventListener('change', () => { S.planEnd = endIn.value || null; save(); renderIndex(); });
    plan.append(el('span', '', T('أختم بحلول')), endIn);
    if (S.planEnd && planDays() < 1) plan.append(el('span', 'hint', T('انتهى موعد الخطة. اختر تاريخاً جديداً.')));
    if (S.planEnd) plan.append(button('link-btn', T('إلغاء الخطة'), (ev) => { ev.preventDefault(); S.planEnd = null; save(); renderIndex(); }));
    const kh = S.khatma.pages.length;
    wird.append(el('span', 'q-kicker', T('ورد اليوم')),
      el('b', 'q-big', `${I.num(done)} / ${I.num(g)} ${T('صفحات')}`), bar, planDays() >= 1 ? el('span') : goalSel, plan,
      el('span', 'q-meta', `${T('الختمة الحالية')}: ${I.num(kh)} / ${I.num(PAGES)}${S.khatma.count ? ` · ${T('ختمات مكتملة')}: ${I.num(S.khatma.count)}` : ''}`));
    top.append(cont, wird);
    root.append(top);

    // Ways to read: the tajweed Mushaf, the teaching Mushaf, and testing what you memorised.
    const modes = el('div', 'q-modes');
    const mode = (on, name, note, run) => {
      const b = button(`q-mode${on ? ' is-on' : ''}`, '', run);
      b.setAttribute('aria-pressed', String(on));
      b.append(el('b', '', T(name)), el('span', '', T(note)));
      modes.append(b);
    };
    if (window.noonMushafBook) mode(false, 'المصحف بتقليب الصفحات', '٦٠٤ صفحات كمصحف المدينة، تقلّبها بيدك', () => window.noonMushafBook.open());
    mode(S.tajweed, 'مصحف التجويد', 'أحكام التجويد ملوّنة في النص', () => { S.tajweed = !S.tajweed; save(); renderIndex(); });
    mode(S.reciter === 'muallim', 'المصحف المعلّم', 'الحصري المعلّم، تكرار الآية ٣ مرات ومهلة لترديدها', () => {
      const on = S.reciter !== 'muallim';
      Object.assign(S, on ? { reciter: 'muallim', repeat: 3, gap: 1, rate: 1 } : { reciter: 'ar.alafasy', repeat: 1, gap: 0 });
      save(); renderIndex();
      if (on) toast(T('فعّلنا المصحف المعلّم. افتح أي سورة واضغط ▶ واستمع ثم ردّد بعد القارئ.'));
    });
    mode(S.hide, 'التسميع والحفظ', 'تُخفى الآيات فتسمّع حفظك، واضغط الآية لتظهر', () => { S.hide = !S.hide; save(); renderIndex(); });
    if (window.noonHifz) {
      const h = window.noonHifz.summary();
      mode(h.due > 0, 'متابعة الحفظ', h.due ? `${I.num(h.due)} ${T('للمراجعة اليوم')}` : T('سجّل ما حفظته ونذكّرك بمراجعته في وقته'), () => window.noonHifz.open());
    }
    if (window.noonKhatma) mode(false, 'الختمة الجماعية', 'اقسموا الختمة على الأجزاء مع أهلك وأصحابك', () => window.noonKhatma.open());
    root.append(modes);

    // Search.
    const form = el('form', 'q-search');
    const input = el('input');
    input.type = 'search'; input.value = query; input.placeholder = T('ابحث بكلمة، أو اكتب ٢:٢٥٥ أو رقم صفحة');
    input.setAttribute('aria-label', T('بحث في المصحف'));
    form.append(input);
    form.addEventListener('submit', (ev) => ev.preventDefault());
    let timer = 0;
    input.addEventListener('input', () => {
      clearTimeout(timer);
      timer = setTimeout(async () => {
        query = input.value.trim();
        if (!query) { found = null; renderList(); return; }
        try { found = await search(query); } catch (_) { found = { error: true }; }
        renderList();
      }, 250);
    });
    root.append(form);

    const segs = el('div', 'filter q-tabs');
    segs.setAttribute('role', 'group');
    [['surahs', 'السور'], ['juz', 'الأجزاء'], ['marks', 'العلامات'], ['kids', 'للأطفال']].forEach(([k, label]) => {
      const b = button('', T(label), () => { tab = k; query = ''; found = null; renderIndex(); });
      b.setAttribute('aria-pressed', String(tab === k && !found));
      segs.append(b);
    });
    root.append(segs);
    const list = el('div', 'q-list');
    list.id = 'qList';
    root.append(list);
    renderList();
    root.append(el('p', 'credit', T('نص المصحف برواية حفص من مشروع تنزيل (tanzil.net)، والترجمة الإنجليزية Sahih International، عبر api.alquran.cloud. التلاوات من cdn.islamic.network، والخط Amiri Quran.')));
  }

  function renderList() {
    const list = $('qList');
    if (!list) return;
    list.replaceChildren();
    list.className = 'q-list';
    if (found) return renderFound(list);
    if (tab === 'surahs') {
      M.surahs.forEach((s, k) => {
        const b = button('q-surah', '', () => open(starts[k]));
        const name = el('span', 'q-surah-name');
        name.append(el('b', '', I.isEn ? s[1] : surahName(k)), el('small', '', I.isEn ? s[2] : s[1]));
        b.append(el('span', 'q-num', I.num(k + 1)), name,
          el('span', 'q-surah-meta', `${T(s[3] === 'M' ? 'مكية' : 'مدنية')} · ${I.num(s[4])} ${T('آية')}`),
          el('span', `q-surah-side${I.isEn ? ' is-ar' : ''}`, I.isEn ? surahNameAr(k) : `${T('صفحة')} ${I.num(pageOf(starts[k]))}`));
        list.append(b);
      });
    } else if (tab === 'kids') {
      // Juz 'Amma for children: the short surahs first, listen and repeat, and up to three stars each.
      S.kids = S.kids || {};
      const done = Object.values(S.kids).reduce((a, n) => a + n, 0);
      list.append(el('p', 'kids-intro', `${T('استمع للشيخ الحصري المعلّم وردّد وراءه، وكل ما تحفظ سورة خد نجمة. نجومك:')} ${'★'.repeat(Math.min(done, 40))} ${I.num(done)}`));
      for (let k = 113; k >= 77; k--) {
        const stars = S.kids[k + 1] || 0;
        const row = el('div', `kids-row${stars >= 3 ? ' is-done' : ''}`);
        const name = el('div', 'kids-name');
        const a = el('b', '', surahNameAr(k)); a.lang = 'ar';
        name.append(a, el('small', '', `${I.isEn ? M.surahs[k][1] + ' · ' : ''}${I.num(M.surahs[k][4])} ${T('آية')}`));
        const st = el('span', 'kids-stars', '★'.repeat(stars) + '☆'.repeat(3 - stars));
        st.setAttribute('aria-label', `${I.num(stars)} / ${I.num(3)}`);
        row.append(name, st,
          button('btn btn-primary', T('استمع وردّد'), () => {
            Object.assign(S, { reciter: 'muallim', repeat: 3, gap: 1, rate: 1 });
            save();
            play(starts[k]); // inside the tap, so the browser allows the sound
            open(starts[k]);
          }),
          button('btn btn-quiet', T('حفظتُها ⭐'), () => {
            S.kids[k + 1] = Math.min(3, stars + 1); save(); renderList();
            if (S.kids[k + 1] === 3) toast(T('ما شاء الله! أتممت حفظ السورة بثلاث نجوم.'));
          }));
        list.append(row);
      }
    } else if (tab === 'juz') {
      list.classList.add('is-grid');
      M.juz.forEach((i, k) => {
        const b = button('q-juz', '', () => open(i));
        b.append(el('b', '', `${T('الجزء')} ${I.num(k + 1)}`), el('span', '', refText(i)));
        list.append(b);
      });
    } else {
      if (!S.marks.length) { list.append(el('p', 'empty', T('لا توجد علامات بعد. اضغط على أي آية أثناء القراءة واختر «علامة».'))); return; }
      S.marks.forEach((m) => {
        const row = el('div', 'q-mark');
        const b = button('q-mark-open', '', () => open(m.i));
        b.append(el('b', '', refText(m.i)), el('span', '', `${T('صفحة')} ${I.num(pageOf(m.i))} · ${new Date(m.at).toLocaleDateString(I.locale, { day: 'numeric', month: 'short' })}`));
        row.append(b, button('link-btn danger', T('إزالة'), () => { toggleMark(m.i); renderList(); }));
        list.append(row);
      });
    }
  }
  const surahNameAr = (k) => M.surahs[k][0].replace(/^سُورَةُ\s*/, '');

  async function renderFound(list) {
    if (found.error) { list.append(el('p', 'empty', T('تعذّر تحميل نص المصحف. تحقّق من الاتصال ثم حاول مرة أخرى.'))); return; }
    if (found.jump !== undefined) { list.append(resultRow(found.jump, await data('uthmani'))); return; }
    if (found.page) {
      const b = button('q-surah', '', () => open(M.pages[found.page - 1]));
      b.append(el('span', 'q-num', I.num(found.page)), el('b', '', `${T('افتح صفحة')} ${I.num(found.page)}`),
        el('span', 'q-surah-meta', refText(M.pages[found.page - 1])));
      list.append(b);
      return;
    }
    const n = found.results.length;
    list.append(el('p', 'view-sub', n ? `${I.num(n)}${n >= 60 ? '+' : ''} ${T('نتيجة')}` : T('لا نتائج. جرّب كلمة أخرى.')));
    if (!n) return;
    const texts = await data('uthmani');
    const en = I.isEn ? await data('en') : null;
    found.results.forEach((i) => list.append(resultRow(i, texts, en)));
  }
  function resultRow(i, texts, en) {
    const b = button('q-result', '', () => open(i));
    const t = el('span', 'q-result-ar', texts[i]);
    t.lang = 'ar'; t.dir = 'rtl';
    b.append(el('b', '', refText(i)), t);
    if (en) { const e = el('span', 'q-result-en', en[i]); e.dir = 'ltr'; b.append(e); }
    return b;
  }

  // ================= the reader (full screen) =================
  let R = null;        // reader elements, built on first open
  let cur = -1;        // surah shown (0-based)
  let sel = -1;        // tapped verse
  let lock = null;     // screen wake lock

  function build() {
    const box = el('div', 'qr');
    box.id = 'quranReader';
    box.setAttribute('role', 'dialog');
    box.setAttribute('aria-modal', 'true');
    box.setAttribute('aria-label', T('المصحف الشريف'));
    box.dir = I.dir;
    box.hidden = true;
    const icon = (d) => `<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${d}" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>`;
    const top = el('header', 'qr-top');
    const close = button('qr-icon', '', () => (history.state && history.state.qr ? history.back() : hide()), T('رجوع لفهرس السور'));
    close.innerHTML = icon('M6 6l12 12M18 6L6 18');
    const title = el('div', 'qr-title');
    const tName = el('b'), tMeta = el('span');
    title.append(tName, tMeta);
    // The menu (☰): reciter, text size, tafsir and the other reading options.
    const menuBtn = button('qr-icon', '', () => { R.settings.hidden = !R.settings.hidden; menuBtn.setAttribute('aria-expanded', String(!R.settings.hidden)); }, T('القائمة'));
    menuBtn.innerHTML = icon('M4 6h16M4 12h16M4 18h16');
    menuBtn.setAttribute('aria-expanded', 'false');
    const playBtn = button('qr-icon qr-play', '', () => (audio.paused || playing < 0 ? play(playing >= 0 ? playing : firstVisible()) : pause()), T('تشغيل التلاوة'));
    playBtn.innerHTML = icon('M8 5v14l11-7z');
    // The reciter, right next to the play button.
    const topRec = el('select', 'qr-reciter');
    topRec.setAttribute('aria-label', T('القارئ'));
    RECITERS.forEach((r) => topRec.append(new Option(I.isEn ? r[3] : r[2], r[0])));
    topRec.value = S.reciter;
    topRec.addEventListener('change', () => setReciter(topRec.value));
    top.append(close, title, topRec, playBtn, menuBtn);

    // Tool row: text size, and quick switches for tafsir, translation and tajweed.
    const tools = el('div', 'qr-tools');
    const zoom = (d) => { S.font = Math.max(20, Math.min(56, S.font + d)); box.style.setProperty('--qf', S.font + 'px'); size.value = String(S.font); save(); };
    const minus = button('qr-chip qr-zoom', 'A−', () => zoom(-2), T('تصغير الخط'));
    const plus = button('qr-chip qr-zoom', 'A+', () => zoom(2), T('تكبير الخط'));
    const quick = (label, key, after) => {
      const b = button('qr-chip', T(label), () => { S[key] = !S[key]; save(); if (after) after(); R.sync(); renderSurah(cur, firstVisible(), true); });
      b.setAttribute('aria-pressed', String(!!S[key]));
      return b;
    };
    const qTafsir = quick('التفسير', 'inlineTafsir');
    const qTrans = quick('الترجمة', 'trans', () => { trans.checked = S.trans; });
    const qTajweed = quick('التجويد', 'tajweed', () => { tj.checked = S.tajweed; legend.hidden = !S.tajweed; });
    const qRules = quick('الأحكام', 'tajRules', () => { tjr.checked = S.tajRules; });
    qRules.title = T('أحكام التجويد مكتوبة تحت كل آية، فوق التفسير');
    // To the page-turning Mushaf, at the page being read.
    const qBook = button('qr-chip', T('تقليب الصفحات'), toBook);
    tools.append(minus, plus, qTafsir, qTrans, qTajweed, qRules, qBook);

    // Reading settings.
    const settings = el('div', 'qr-settings');
    settings.hidden = true;
    const size = el('input'); size.type = 'range'; size.min = '20'; size.max = '56'; size.step = '2'; size.value = String(S.font);
    size.setAttribute('aria-label', T('حجم الخط'));
    size.addEventListener('input', () => { S.font = Number(size.value); box.style.setProperty('--qf', S.font + 'px'); save(); });
    const trans = el('input'); trans.type = 'checkbox'; trans.checked = S.trans;
    trans.addEventListener('change', () => { S.trans = trans.checked; qTrans.setAttribute('aria-pressed', String(S.trans)); save(); renderSurah(cur, firstVisible(), true); });
    const transRow = el('div', 'qr-row qr-check');
    const tLab = el('label', 'qr-row'); tLab.append(trans, el('span', '', T('الترجمة')));
    const tSel = el('select');
    tSel.setAttribute('aria-label', T('لغة الترجمة'));
    TRANS.forEach(([v, n]) => tSel.append(new Option(n, v)));
    tSel.value = transLang();
    tSel.addEventListener('change', () => { S.transLang = tSel.value; S.trans = true; trans.checked = true; save(); renderSurah(cur, firstVisible(), true); });
    transRow.append(tLab, tSel);
    const rec = el('select');
    rec.setAttribute('aria-label', T('القارئ'));
    RECITERS.forEach((r) => rec.append(new Option(I.isEn ? r[3] : r[2], r[0])));
    rec.value = S.reciter;
    rec.addEventListener('change', () => setReciter(rec.value));
    function setReciter(v) {
      S.reciter = v; rec.value = v; topRec.value = v; save();
      if (playing >= 0 && !audio.paused) play(playing);
    }
    const tfSel = el('select');
    tfSel.setAttribute('aria-label', T('التفسير المعروض'));
    TAFSIRS.forEach((x) => tfSel.append(new Option(I.isEn ? x[2] : x[1], x[0])));
    tfSel.value = S.tafsir;
    tfSel.addEventListener('change', () => { S.tafsir = tfSel.value; save(); if (S.inlineTafsir) renderSurah(cur, firstVisible(), true); });
    const tfRow = el('label', 'qr-row'); tfRow.append(el('span', '', T('التفسير المعروض')), tfSel);
    const tfShow = el('input'); tfShow.type = 'checkbox'; tfShow.checked = !!S.inlineTafsir;
    tfShow.addEventListener('change', () => { S.inlineTafsir = tfShow.checked; qTafsir.setAttribute('aria-pressed', String(S.inlineTafsir)); save(); renderSurah(cur, firstVisible(), true); });
    const tfShowRow = el('label', 'qr-row qr-check'); tfShowRow.append(tfShow, el('span', '', T('اعرض التفسير تحت كل آية')));
    const indexBtn = button('btn btn-quiet', T('فهرس السور'), () => close.click());
    // Text size: the buttons and the slider in one row.
    const sizeBtns = el('div', 'qr-row qr-size');
    sizeBtns.append(el('span', '', T('حجم الخط')), button('qr-chip qr-zoom', 'A−', () => zoom(-2), T('تصغير الخط')), size, button('qr-chip qr-zoom', 'A+', () => zoom(2), T('تكبير الخط')));
    const recRow = el('label', 'qr-row'); recRow.append(el('span', '', T('القارئ')), rec);
    const themes = el('div', 'qr-row qr-themes');
    themes.append(el('span', '', T('لون الصفحة')));
    [['paper', 'فاتح'], ['sepia', 'ورقي'], ['night', 'ليلي']].forEach(([k, label]) => {
      const b = button(`qr-theme qr-theme-${k}`, T(label), () => { S.theme = k; box.dataset.theme = k; save(); themes.querySelectorAll('button').forEach((x) => x.setAttribute('aria-pressed', String(x === b))); });
      b.setAttribute('aria-pressed', String(S.theme === k));
      themes.append(b);
    });
    const tj = el('input'); tj.type = 'checkbox'; tj.checked = S.tajweed;
    const legend = el('div', 'qr-legend');
    legend.hidden = !S.tajweed;
    TAJWEED.forEach(([k, a, e]) => { const x = el('span', `tj-${k}`); x.append(el('i'), I.isEn ? e : a); legend.append(x); });
    tj.addEventListener('change', () => { S.tajweed = tj.checked; legend.hidden = !S.tajweed; qTajweed.setAttribute('aria-pressed', String(S.tajweed)); save(); renderSurah(cur, firstVisible(), true); });
    const tjRow = el('label', 'qr-row qr-check'); tjRow.append(tj, el('span', '', T('مصحف التجويد (ألوان الأحكام)')));
    const tjr = el('input'); tjr.type = 'checkbox'; tjr.checked = !!S.tajRules;
    tjr.addEventListener('change', () => { S.tajRules = tjr.checked; qRules.setAttribute('aria-pressed', String(S.tajRules)); save(); renderSurah(cur, firstVisible(), true); });
    const tjrRow = el('label', 'qr-row qr-check'); tjrRow.append(tjr, el('span', '', T('أحكام التجويد مكتوبة فوق التفسير')));
    const hide = el('input'); hide.type = 'checkbox'; hide.checked = S.hide;
    hide.addEventListener('change', () => { S.hide = hide.checked; save(); R.page.classList.toggle('is-hide', S.hide); R.page.querySelectorAll('.is-shown').forEach((n) => n.classList.remove('is-shown')); });
    const hideRow = el('label', 'qr-row qr-check'); hideRow.append(hide, el('span', '', T('التسميع: إخفاء الآيات حتى تضغط عليها')));
    const pick = (label, key, opts, after) => {
      const sel = el('select');
      sel.setAttribute('aria-label', T(label));
      opts.forEach(([v, t]) => sel.append(new Option(T(t), String(v))));
      sel.value = String(S[key]);
      sel.addEventListener('change', () => { S[key] = Number(sel.value); save(); if (after) after(); });
      const row = el('label', 'qr-row'); row.append(el('span', '', T(label)), sel);
      return row;
    };
    const learn = el('div', 'qr-learn');
    learn.append(el('b', '', T('التعلّم والحفظ')),
      pick('تكرار كل آية', 'repeat', [[1, 'مرة واحدة'], [2, 'مرتان'], [3, '٣ مرات'], [5, '٥ مرات'], [10, '١٠ مرات']]),
      pick('مهلة للترديد بعد الآية', 'gap', [[0, 'بدون'], [0.5, 'نصف مدة الآية'], [1, 'مثل مدة الآية'], [1.5, 'مرة ونصف']]),
      pick('سرعة التلاوة', 'rate', [[0.75, 'أبطأ'], [1, 'عادية'], [1.25, 'أسرع']], () => { audio.playbackRate = S.rate; }),
      hideRow);
    settings.append(indexBtn, recRow, sizeBtns, tfRow, tfShowRow, transRow, tjRow, legend, tjrRow, themes, learn);

    const body = el('div', 'qr-body');
    body.tabIndex = -1;
    const page = el('div', 'qr-page');
    body.append(page);

    // Verse actions.
    const sheet = el('div', 'qr-sheet');
    sheet.hidden = true;
    const sheetHead = el('div', 'qr-sheet-head');
    const sheetTitle = el('b');
    const sheetX = button('qr-icon', '', () => unselect(), T('إغلاق'));
    sheetX.innerHTML = icon('M6 6l12 12M18 6L6 18');
    sheetHead.append(sheetTitle, sheetX);
    const acts = el('div', 'qr-acts');
    const tafsir = el('div', 'qr-tafsir');
    tafsir.hidden = true;
    sheet.append(sheetHead, acts, tafsir);
    tafsir.addEventListener('click', (ev) => { if (ev.target.closest('.ay-tj')) rulesClick(ev); });

    box.append(top, tools, settings, body, sheet);
    document.body.append(box);
    box.style.setProperty('--qf', S.font + 'px');
    box.dataset.theme = S.theme;

    body.addEventListener('click', (ev) => {
      if (ev.target.closest('.ay-tj')) return rulesClick(ev); // the rules under a verse: highlight, explain
      const a = ev.target.closest('[data-i]');
      // In memorisation mode the first tap only reveals the verse.
      if (a && S.hide && !a.classList.contains('is-shown')) { a.classList.add('is-shown'); return; }
      if (a) select(Number(a.dataset.i));
      const nav = ev.target.closest('[data-go]');
      if (nav) renderSurah(Number(nav.dataset.go), null);
    });
    body.addEventListener('scroll', onScroll, { passive: true });
    box.addEventListener('keydown', (ev) => {
      if (ev.key === 'Escape') { if (!sheet.hidden) unselect(); else if (!settings.hidden) settings.hidden = true; else close.click(); }
    });
    // Options can also change from the index (tajweed, teaching Mushaf, memorisation): refresh on open.
    const sync = () => {
      size.value = String(S.font); trans.checked = S.trans; tSel.value = transLang(); rec.value = S.reciter; topRec.value = S.reciter;
      tj.checked = S.tajweed; legend.hidden = !S.tajweed; tjr.checked = !!S.tajRules; qRules.setAttribute('aria-pressed', String(!!S.tajRules)); hide.checked = S.hide; tfSel.value = S.tafsir; tfShow.checked = !!S.inlineTafsir;
      qTafsir.setAttribute('aria-pressed', String(!!S.inlineTafsir)); qTrans.setAttribute('aria-pressed', String(!!S.trans)); qTajweed.setAttribute('aria-pressed', String(!!S.tajweed));
      learn.querySelectorAll('select').forEach((x, k) => { x.value = String(S[['repeat', 'gap', 'rate'][k]]); });
      box.style.setProperty('--qf', S.font + 'px'); box.dataset.theme = S.theme;
    };
    R = { box, tName, tMeta, settings, body, page, sheet, sheetTitle, acts, tafsir, playBtn, trans, sync };
  }

  // at: the verse to show; keep: put it at the top without a flash (after a layout change).
  function renderSurah(s, at, keep) {
    // The tajweed text and the translations are fetched the first time they are switched on.
    if ((S.tajweed || S.tajRules) && !txt.tajweed) {
      data('tajweed').then(() => renderSurah(s, at, keep)).catch(() => { S.tajweed = false; S.tajRules = false; renderSurah(s, at, keep); });
      return;
    }
    if (S.inlineTafsir && !surahTafsirs[`${S.tafsir}:${s}`]) {
      R.page.replaceChildren(el('p', 'qr-loading', T('جارٍ تحميل التفسير…')));
      loadSurahTafsir(s).then(() => renderSurah(s, at, keep)).catch(() => {
        toast(T('التفسير يحتاج اتصالاً بالإنترنت. حاول مرة أخرى.'));
        S.inlineTafsir = false; renderSurah(s, at, keep);
      });
      return;
    }
    const tl = transLang();
    if (S.trans && tl !== 'en' && !transCache[`${tl}:${s}`]) {
      fetch(`https://api.alquran.cloud/v1/surah/${s + 1}/${tl}`).then((r) => r.json()).then((j) => {
        transCache[`${tl}:${s}`] = j.data.ayahs.map((a) => a.text);
        renderSurah(s, at, keep);
      }).catch(() => { toast(T('الترجمات غير الإنجليزية تحتاج اتصالاً بالإنترنت.')); S.transLang = 'en'; renderSurah(s, at, keep); });
      return;
    }
    if (S.trans && tl === 'en' && !txt.en) {
      data('en').then(() => renderSurah(s, at, keep)).catch(() => { S.trans = false; R.trans.checked = false; renderSurah(s, at, keep); });
      return;
    }
    cur = s;
    sel = -1;
    R.sheet.hidden = true;
    const texts = txt.uthmani;
    const first = starts[s], count = M.surahs[s][4];
    const frag = document.createDocumentFragment();
    const head = el('div', 'qr-head');
    const frame = el('div', 'qr-frame');
    frame.append(el('span', 'qr-frame-name', M.surahs[s][0]));
    frame.lang = 'ar';
    head.append(frame, el('p', 'qr-head-meta', `${I.isEn ? `${M.surahs[s][1]} · ${M.surahs[s][2]} · ` : ''}${T(M.surahs[s][3] === 'M' ? 'مكية' : 'مدنية')} · ${I.num(count)} ${T('آية')}`));
    frag.append(head);
    if (s !== 0 && s !== 8) {
      const b = el('p', 'qr-basmala', M.basmala);
      b.lang = 'ar';
      frag.append(b);
      if (S.trans && transLang() === 'en') { const e = el('p', 'qr-basmala-en', M.basmalaEn); e.dir = 'ltr'; e.lang = 'en'; frag.append(e); }
    }
    const blocks = S.trans || S.inlineTafsir || S.tajRules; // one verse per block, with its rules / translation / tafsir
    let pg = null, flow = null, p = 0;
    for (let i = first; i < first + count; i++) {
      const pi = pageOf(i);
      if (pi !== p) {
        if (pg) pg.append(foot(p));
        p = pi;
        pg = el('section', 'qr-pg');
        pg.dataset.page = String(p);
        flow = blocks ? pg : el('p', 'qr-flow');
        if (!blocks) { flow.lang = 'ar'; flow.dir = 'rtl'; pg.append(flow); }
        frag.append(pg);
      }
      const n = el('span', 'ay-n', '۝' + ar(i - first + 1));
      if (blocks) {
        const blk = el('div', 'ay-b');
        blk.dataset.i = String(i);
        const a = el('p', 'ay-ar');
        a.lang = 'ar'; a.dir = 'rtl';
        a.append(verse(i), ' ', n);
        if (sajda.has(i)) a.append(el('span', 'ay-sajda', '۩'));
        blk.append(a);
        if (S.tajRules && txt.tajweed) blk.append(rulesBlock(i));
        if (S.trans) {
          const e = el('p', 'ay-en');
          e.dir = 'auto'; e.lang = transLang().split('.')[0];
          e.append(el('b', '', `${s + 1}:${i - first + 1} `), transText(s, i));
          blk.append(e);
        }
        const tf = S.inlineTafsir && (surahTafsirs[`${S.tafsir}:${s}`] || [])[i - first];
        if (tf) {
          const t = el('div', 'ay-tf');
          t.lang = S.tafsir.startsWith('en') ? 'en' : 'ar'; t.dir = S.tafsir.startsWith('en') ? 'ltr' : 'rtl';
          tf.split(/\n+/).filter((x) => x.trim()).forEach((para) => t.append(el('p', '', para.trim())));
          blk.append(t);
        }
        if (isMarked(i)) blk.classList.add('is-mark');
        flow.append(blk);
      } else {
        const a = el('span', 'ay');
        a.dataset.i = String(i);
        a.append(verse(i), ' ', n);
        if (sajda.has(i)) a.append(el('span', 'ay-sajda', '۩'));
        if (isMarked(i)) a.classList.add('is-mark');
        flow.append(a, ' ');
      }
    }
    if (pg) pg.append(foot(p));
    const nav = el('div', 'qr-nav');
    if (s > 0) { const b = button('btn btn-quiet', `${T('السورة السابقة')}: ${surahName(s - 1)}`); b.dataset.go = String(s - 1); nav.append(b); }
    if (s < 113) { const b = button('btn btn-primary', `${T('السورة التالية')}: ${surahName(s + 1)}`); b.dataset.go = String(s + 1); nav.append(b); }
    frag.append(nav);
    R.page.replaceChildren(frag);
    R.page.classList.toggle('is-hide', !!S.hide);
    R.tName.textContent = I.isEn ? `${M.surahs[s][1]}` : surahName(s);
    observe();
    if (at !== null && at !== undefined && at > first) {
      const target = R.page.querySelector(`[data-i="${at}"]`);
      if (target && keep) target.scrollIntoView({ block: 'start' });
      else if (target) { target.scrollIntoView({ block: 'center' }); flash(target); }
    } else R.body.scrollTop = 0;
    updateMeta(at !== null && at !== undefined ? at : first);
    if (playing >= 0) highlight(playing);
  }
  // A verse's text: plain, or from the tajweed edition, its rules coloured (S.tajweed) and each
  // marked run tagged with its marks (data-m), so a rule listed under the verse can light it up.
  const TJ = window.noonTajweedCore, RULES = window.NOON_TAJWEED_RULES || {};
  function verse(i) {
    if (!(S.tajweed || S.tajRules) || !txt.tajweed || !TJ) return txt.uthmani[i];
    const f = document.createDocumentFragment();
    TJ.segments(txt.tajweed[i]).forEach((g) => {
      if (!g.code) { f.append(g.text); return; }
      const sp = el('span', S.tajweed ? `tj-${g.code}` : '', g.text);
      sp.dataset.m = g.m.join(' ');
      f.append(sp);
    });
    return f;
  }
  // «أحكام التجويد» for one verse: each rule in its colour with the words it falls on.
  function rulesBlock(i) {
    const box = el('div', 'ay-tj');
    box.dataset.v = String(i);
    box.append(el('b', 'ay-tj-head', T('أحكام التجويد')));
    const groups = TJ.rules(txt.tajweed[i]);
    if (!groups.length) box.append(el('span', 'hint', T('لا أحكام معلَّمة في هذه الآية.')));
    groups.forEach((g) => {
      const r = RULES[g.code];
      if (!r) return;
      const row = el('div', 'ay-tj-row');
      const name = button(`ay-tj-name tj-${g.code}`, '');
      name.append(el('i'), I.isEn ? r.en : r.ar);
      name.dataset.def = g.code;
      name.setAttribute('aria-expanded', 'false');
      row.append(name);
      g.items.forEach((it) => {
        const w = button('ay-tj-word', it.word);
        w.lang = 'ar';
        w.dataset.ks = it.ks.join(' ');
        row.append(w);
      });
      const def = el('p', 'ay-tj-def', I.isEn ? r.defEn : r.defAr);
      def.hidden = true;
      row.append(def);
      box.append(row);
    });
    return box;
  }
  function rulesClick(ev) {
    const name = ev.target.closest('[data-def]');
    if (name) {
      const def = name.parentNode.querySelector('.ay-tj-def');
      def.hidden = !def.hidden;
      name.setAttribute('aria-expanded', String(!def.hidden));
      return;
    }
    const w = ev.target.closest('.ay-tj-word');
    if (!w) return;
    const box = w.closest('.ay-tj'), ks = w.dataset.ks.split(' ');
    const host = R.box.querySelector(`[data-i="${box.dataset.v}"]`) || box.parentNode;
    R.box.querySelectorAll('.is-hit').forEach((n) => n.classList.remove('is-hit'));
    const hits = [...host.querySelectorAll('[data-m]')].filter((n) => n.dataset.m.split(' ').some((k) => ks.includes(k)));
    hits.forEach((n) => n.classList.add('is-hit'));
    clearTimeout(rulesClick.t);
    rulesClick.t = setTimeout(() => hits.forEach((n) => n.classList.remove('is-hit')), 2600);
  }
  function foot(p) {
    const f = el('div', 'qr-pg-foot');
    f.dataset.page = String(p);
    f.append(el('span', '', I.num(p)));
    return f;
  }
  function flash(node) { node.classList.add('is-flash'); setTimeout(() => node.classList.remove('is-flash'), 1600); }
  function updateMeta(i) {
    R.tMeta.textContent = `${T('الجزء')} ${I.num(juzOf(i))} · ${T('صفحة')} ${I.num(pageOf(i))}`;
  }

  // A page counts as read once it has been on screen for 20 seconds in all,
  // so scrolling past or jumping over pages doesn't inflate the wird.
  const DWELL = 20, TICK = 2;
  let dwell = {};
  function observe() { dwell = {}; }
  setInterval(() => {
    if (!R || R.box.hidden || document.hidden) return;
    const b = R.body.getBoundingClientRect();
    R.page.querySelectorAll('.qr-pg').forEach((pg) => {
      const r = pg.getBoundingClientRect();
      if (r.bottom <= b.top + 40 || r.top >= b.bottom - 40) return;
      const p = Number(pg.dataset.page);
      dwell[p] = (dwell[p] || 0) + TICK;
      if (dwell[p] === DWELL) markPage(p);
    });
  }, TICK * 1000);
  function firstVisible() {
    const top = R.body.getBoundingClientRect().top + 60;
    const all = R.page.querySelectorAll('[data-i]');
    for (const a of all) { const r = a.getBoundingClientRect(); if (r.bottom > top) return Number(a.dataset.i); }
    return starts[cur];
  }
  let scrollT = 0, settleT = 0;
  function onScroll() {
    clearTimeout(settleT);
    settleT = setTimeout(settle, 220); // once the scrolling stops
    if (scrollT) return;
    scrollT = setTimeout(() => {
      scrollT = 0;
      if (R.box.hidden) return;
      const i = firstVisible();
      updateMeta(i);
      setLast(i);
    }, 300);
  }
  // No verse line is left cut by the top edge: when the scrolling stops, the page moves the little
  // it takes to show that line whole (js/mushaf-core.js decides which way). The bottom edge fades,
  // so a line it cuts shows that the verse goes on.
  function settle() {
    if (!R || R.box.hidden || !window.noonMushafCore || R.body.scrollTop < 4) return;
    const top = R.body.getBoundingClientRect().top, lines = [], range = document.createRange();
    R.page.querySelectorAll('.ay, .ay-ar').forEach((v) => {
      const b = v.getBoundingClientRect();
      if (b.bottom < top - 4 || b.top > top + 4) return; // only the verse under the top edge
      range.selectNodeContents(v);
      for (const r of range.getClientRects()) if (r.height > 4) lines.push({ top: r.top, bottom: r.bottom });
    });
    // Rects of one line overlap (a verse number, a mark): merge them into whole lines.
    lines.sort((a, b) => a.top - b.top);
    const merged = [];
    lines.forEach((l) => { const m = merged[merged.length - 1]; if (m && l.top < m.bottom - 2) m.bottom = Math.max(m.bottom, l.bottom); else merged.push({ ...l }); });
    const d = window.noonMushafCore.cutDelta(merged, top);
    if (Math.abs(d) > 1) R.body.scrollBy({ top: d, behavior: 'smooth' });
  }

  function select(i) {
    unselect(true);
    sel = i;
    const node = R.page.querySelector(`[data-i="${i}"]`);
    if (node) node.classList.add('is-sel');
    R.sheetTitle.textContent = refText(i);
    R.tafsir.hidden = true;
    R.tafsir.replaceChildren();
    R.sheet.classList.remove('is-tall');
    const texts = txt.uthmani;
    const share = `${texts[i]} ﴿${surahNameAr(surahOf(i))} ${ar(ayahOf(i))}﴾`;
    R.acts.replaceChildren(
      button('qr-act', T('تشغيل من هنا'), () => { play(i); unselect(); }),
      button('qr-act', T(isMarked(i) ? 'إزالة العلامة' : 'علامة'), () => {
        toggleMark(i);
        if (node) node.classList.toggle('is-mark', isMarked(i));
        toast(T(isMarked(i) ? 'حُفظت العلامة.' : 'أُزيلت العلامة.'));
        unselect();
      }),
      button('qr-act', T('التفسير'), () => tafsirOf(i)),
      button('qr-act', T('كلمة بكلمة'), () => wordByWord(i)),
      button('qr-act', T('نسخ'), () => copy(share)),
      button('qr-act', T('مشاركة'), async () => {
        if (navigator.share) { try { await navigator.share({ text: share }); } catch (_) {} } else copy(share);
      }),
      button('qr-act', T('توقّفت هنا'), () => { setLast(i); toast(T('حُفظ موضع القراءة.')); unselect(); }),
      button('qr-act', T('أضف لكروت الحفظ'), () => {
        if (!window.noonCards) return;
        // Front: the verse before it (or where the surah starts); back: the verse to recall.
        const s0 = surahOf(i);
        const front = i > starts[s0] ? `${T('ما الآية التالية؟')}\n${texts[i - 1]}` : `${T('أول سورة')} ${surahNameAr(s0)}`;
        const ok = window.noonCards.add(T('حفظ القرآن'), front, `${texts[i]} ﴿${ar(ayahOf(i))}﴾`);
        toast(T(ok ? 'أُضيفت الآية إلى مجموعة «حفظ القرآن» في الكروت.' : 'هذه الآية موجودة في كروت الحفظ.'));
      }),
      button('qr-act', T('مشاركة ككارت'), () => window.noonCard && window.noonCard.shareImage({
        kicker: T('القرآن الكريم'), title: refText(i), body: texts[i], quran: true, ref: `﴿${surahNameAr(surahOf(i))} ${ar(ayahOf(i))}﴾`
      }))
    );
    R.sheet.hidden = false;
  }
  function unselect(keepSheet) {
    const old = R.page.querySelector('.is-sel');
    if (old) old.classList.remove('is-sel');
    sel = -1;
    if (!keepSheet) { R.sheet.hidden = true; R.sheet.classList.remove('is-tall'); }
  }
  async function copy(text) {
    try { await navigator.clipboard.writeText(text); toast(T('نُسخت الآية.')); } catch (_) { toast(T('تعذّر النسخ.')); }
  }
  // Word by word, from Quran.com: meaning, transliteration, and the word's own recitation on tap.
  let wordAudio = null;
  async function wordByWord(i) {
    R.sheet.classList.add('is-tall');
    R.tafsir.hidden = false;
    R.tafsir.replaceChildren(el('p', 'hint', T('جارٍ تحميل معاني الكلمات…')));
    const lang = I.isEn ? 'en' : (['ur', 'id', 'tr', 'bn'].includes(transLang().split('.')[0]) ? transLang().split('.')[0] : 'en');
    try {
      const r = await fetch(`https://api.quran.com/api/v4/verses/by_key/${surahOf(i) + 1}:${ayahOf(i)}?words=true&word_fields=text_uthmani&language=${lang}`);
      const j = await r.json();
      if (sel !== i) return;
      const grid = el('div', 'wbw');
      j.verse.words.filter((w) => w.char_type_name === 'word').forEach((w) => {
        const b = button('wbw-word', '', () => {
          if (!w.audio_url) return;
          wordAudio = wordAudio || new Audio();
          wordAudio.src = `https://audio.qurancdn.com/${w.audio_url}`;
          wordAudio.play().catch(() => {});
        });
        const a = el('b', '', w.text_uthmani || w.text); a.lang = 'ar';
        b.append(a, el('span', 'wbw-tr', (w.transliteration && w.transliteration.text) || ''), el('span', 'wbw-mean', (w.translation && w.translation.text) || ''));
        grid.append(b);
      });
      R.tafsir.replaceChildren(el('b', '', T('كلمة بكلمة')), el('p', 'hint', T('اضغط الكلمة لتسمع نطقها. المعاني من Quran.com.')), grid);
    } catch (_) {
      R.tafsir.replaceChildren(el('p', 'hint', T('معاني الكلمات تحتاج اتصالاً بالإنترنت. حاول مرة أخرى.')));
    }
  }
  // A whole surah's tafsir, for reading it under the verses.
  const surahTafsirs = {};
  async function loadSurahTafsir(s) {
    const t = TAFSIRS.find((x) => x[0] === S.tafsir) || TAFSIRS[0];
    let list;
    if (t[3] === 'alq') {
      const j = await (await fetch(`https://api.alquran.cloud/v1/surah/${s + 1}/${t[4]}`)).json();
      list = j.data.ayahs.map((a) => a.text);
    } else {
      const r = await fetch(`https://cdn.jsdelivr.net/gh/spa5k/tafsir_api@main/tafsir/${t[4]}/${s + 1}.json`);
      if (!r.ok) throw new Error(r.status);
      const rows = await r.json();
      list = [];
      (Array.isArray(rows) ? rows : rows.ayahs || []).forEach((x) => { list[x.ayah - 1] = x.text || ''; });
    }
    surahTafsirs[`${S.tafsir}:${s}`] = list;
  }
  async function tafsirText(t, i) {
    if (t[3] === 'alq') {
      const j = await (await fetch(`https://api.alquran.cloud/v1/ayah/${i + 1}/${t[4]}`)).json();
      return j.data.text;
    }
    const r = await fetch(`https://cdn.jsdelivr.net/gh/spa5k/tafsir_api@main/tafsir/${t[4]}/${surahOf(i) + 1}/${ayahOf(i)}.json`);
    if (!r.ok) throw new Error(r.status);
    return (await r.json()).text || '';
  }
  async function tafsirOf(i) {
    R.sheet.classList.add('is-tall');
    R.tafsir.hidden = false;
    const t = TAFSIRS.find((x) => x[0] === S.tafsir) || TAFSIRS[0];
    const pickT = el('select');
    pickT.setAttribute('aria-label', T('اختر التفسير'));
    TAFSIRS.forEach((x) => pickT.append(new Option(I.isEn ? x[2] : x[1], x[0])));
    pickT.value = t[0];
    pickT.addEventListener('change', () => { S.tafsir = pickT.value; save(); tafsirOf(i); });
    R.tafsir.replaceChildren(pickT, el('p', 'hint', T('جارٍ تحميل التفسير…')));
    try {
      // Some tafsirs explain a group of verses once, under its first verse.
      let k = i, text = await tafsirText(t, k);
      const s0 = starts[surahOf(i)];
      while (!text.trim() && k > s0 && i - k < 12) { k--; text = await tafsirText(t, k); }
      if (sel !== i) return;
      const p = el('div', 'qr-tafsir-text');
      p.lang = t[0].startsWith('en') ? 'en' : 'ar';
      p.dir = t[0].startsWith('en') ? 'ltr' : 'rtl';
      text.split(/\n+/).filter((x) => x.trim()).forEach((para) => p.append(el('p', '', para.trim())));
      const parts = [pickT];
      // The verse's tajweed rules sit above its tafsir, when they are switched on.
      if (S.tajRules && TJ) { try { await data('tajweed'); parts.push(rulesBlock(i)); } catch (_) {} }
      if (k !== i) parts.push(el('p', 'hint', `${T('تفسير هذه الآية مع ما قبلها، من الآية')} ${I.num(ayahOf(k))}`));
      parts.push(p, el('span', 'hint', t[3] === 'alq' ? T('المصدر: api.alquran.cloud') : T('المصدر: spa5k/tafsir_api عبر jsDelivr')));
      R.tafsir.replaceChildren(...parts);
    } catch (_) {
      R.tafsir.replaceChildren(pickT, el('p', 'hint', T('التفسير يحتاج اتصالاً بالإنترنت. حاول مرة أخرى.')));
    }
  }

  // ---- recitation, verse by verse ----
  const audio = new Audio();
  audio.preload = 'auto';
  let playing = -1;
  const nextAudio = new Audio();
  nextAudio.preload = 'auto';
  const reciter = () => RECITERS.find((r) => r[0] === S.reciter) || RECITERS[0];
  const src = (i) => (reciter()[4] ? reciter()[4](i) : `https://cdn.islamic.network/quran/audio/${reciter()[1]}/${reciter()[0]}/${i + 1}.mp3`);
  let left = 0, gapTimer = 0; // repeats still to play; the pause before the next one
  function play(i, again) {
    clearTimeout(gapTimer);
    if (!again) left = Math.max(1, S.repeat || 1);
    playing = i;
    audio.src = src(i);
    audio.playbackRate = S.rate || 1;
    audio.play().then(() => window.dispatchEvent(new CustomEvent('noon-recitation'))).catch(() => {
      toast(T('تعذّر تشغيل التلاوة. التلاوة تحتاج اتصالاً بالإنترنت.'));
      stopped();
    });
    const end = starts[surahOf(i)] + M.surahs[surahOf(i)][4];
    if (i + 1 < end) nextAudio.src = src(i + 1);
    if (R) {
      if (surahOf(i) !== cur && !R.box.hidden) renderSurah(surahOf(i), i);
      highlight(i, true);
    }
    if ('mediaSession' in navigator) {
      try {
        navigator.mediaSession.metadata = new MediaMetadata({ title: refText(i), artist: I.isEn ? reciter()[3] : reciter()[2], album: T('القرآن الكريم') });
        navigator.mediaSession.setActionHandler('pause', pause);
        navigator.mediaSession.setActionHandler('play', () => play(playing));
        navigator.mediaSession.setActionHandler('nexttrack', () => { if (playing + 1 < TOTAL) play(playing + 1); });
        navigator.mediaSession.setActionHandler('previoustrack', () => { if (playing > 0) play(playing - 1); });
      } catch (_) {}
    }
    setPlayIcon(true);
  }
  function pause() { clearTimeout(gapTimer); audio.pause(); setPlayIcon(false); }
  // The Listen tab started to play.
  window.addEventListener('noon-recitation', (ev) => { if (ev.detail && /^listen/.test(ev.detail.from) && playing >= 0) pause(); }); // also between two verses
  function stopped() { playing = -1; setPlayIcon(false); if (R) R.page.querySelectorAll('.is-play').forEach((n) => n.classList.remove('is-play')); }
  audio.addEventListener('ended', () => {
    const s = surahOf(playing), end = starts[s] + M.surahs[s][4];
    const wait = (S.gap || 0) * (audio.duration || 0) * 1000 / (S.rate || 1);
    const next = () => {
      if (--left > 0) play(playing, true);
      else if (playing + 1 < end) play(playing + 1);
      else stopped();
    };
    if (wait > 0) gapTimer = setTimeout(next, wait); else next();
  });
  function highlight(i, scroll) {
    if (!R) return;
    R.page.querySelectorAll('.is-play').forEach((n) => n.classList.remove('is-play'));
    const node = R.page.querySelector(`[data-i="${i}"]`);
    if (!node) return;
    node.classList.add('is-play');
    if (scroll && !R.box.hidden) {
      const r = node.getBoundingClientRect(), b = R.body.getBoundingClientRect();
      if (r.top < b.top + 40 || r.bottom > b.bottom - 40) node.scrollIntoView({ block: 'center', behavior: 'smooth' });
    }
  }
  function setPlayIcon(on) {
    if (!R) return;
    R.playBtn.innerHTML = on
      ? '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M8 5v14M16 5v14" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round"/></svg>'
      : '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M8 5v14l11-7z" fill="none" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/></svg>';
    R.playBtn.setAttribute('aria-label', T(on ? 'إيقاف التلاوة مؤقتاً' : 'تشغيل التلاوة'));
  }

  // ---- open / close ----
  async function open(i) {
    if (!R) build();
    R.sync();
    R.box.hidden = false;
    document.body.classList.add('qr-open');
    if (!history.state || !history.state.qr) history.pushState({ qr: 1 }, '');
    R.page.replaceChildren(el('p', 'qr-loading', T('جارٍ فتح المصحف…')));
    try {
      await Promise.all([data('uthmani'), S.trans ? data('en') : null, fontReady()]);
    } catch (_) {
      R.page.replaceChildren(el('p', 'qr-loading', T('تعذّر تحميل نص المصحف. تحقّق من الاتصال ثم حاول مرة أخرى.')));
      return;
    }
    renderSurah(surahOf(i), i);
    setLast(i);
    R.body.focus({ preventScroll: true }); // keyboard scrolling works straight away
    keepAwake();
  }
  function hide() {
    if (!R || R.box.hidden) return;
    R.box.hidden = true;
    document.body.classList.remove('qr-open');
    if (lock) { lock.release().catch(() => {}); lock = null; }
    // Back to the Mushaf's own index (the surah list), not wherever the page was.
    // (After the back button the browser restores an old scroll position, so wait for it.)
    window.noonUI.show('quran');
    renderIndex();
    setTimeout(() => root.scrollIntoView({ block: 'start' }), 60);
  }
  addEventListener('popstate', () => { if (R && !R.box.hidden) hide(); });
  // From the reader to the page-turning Mushaf, at the page being read. (Inside build() "hide" is the
  // memorisation checkbox, so the reader is closed from out here.)
  function toBook() {
    if (!window.noonMushafBook) return;
    const p = pageOf(firstVisible());
    hide();
    window.noonMushafBook.open(p);
  }
  async function keepAwake() {
    try { if ('wakeLock' in navigator && !lock) { lock = await navigator.wakeLock.request('screen'); lock.addEventListener('release', () => { lock = null; }); } } catch (_) {}
  }
  document.addEventListener('visibilitychange', () => { if (!document.hidden && R && !R.box.hidden) keepAwake(); });

  onRemote(KEY, () => { S = Object.assign(blank(), load(KEY, {})); fresh(); if (!root.hidden) renderIndex(); });
  window.addEventListener('noon-hifz', () => { if (!root.hidden) renderIndex(); }); // the memorisation card's count
  window.addEventListener('noon-view', (ev) => { if (ev.detail.view === 'quran') renderIndex(); });
  setInterval(() => { if (S.today.day !== dayKey()) { fresh(); if (!root.hidden) renderIndex(); } }, 60000);
  // For the page-turning Mushaf (js/mushaf-book.js): the texts, the reading progress and its last page.
  const book = {
    load: () => Promise.all([data('uthmani'), S.tajweed ? data('tajweed').catch(() => null) : null, fontReady()]),
    verse, starts, surahOf, ayahOf, pageOf, juzOf, ar, sajda, markPage, setLast,
    theme: () => S.theme, page: () => S.bookPage || (S.last ? pageOf(S.last.i) : 1),
    setPage: (p) => { if (S.bookPage !== p) { S.bookPage = p; save(); } },
    openAt: (i) => open(i)
  };
  window.noonQuran = { book, openSurah: (s) => open(starts[s - 1]), progress: () => ({ today: S.today.pages.length, goal: goal() }), openAyah: (s, a) => open(starts[s - 1] + Math.max(0, a - 1)), last: () => (S.last ? { i: S.last.i, label: refText(S.last.i) } : null), pagesOn: (day) => ((S.log || {})[day] || 0) };
  renderIndex();
})();
