// Generated by tools/build_salah.py from the hadith collections. Do not edit by hand.
window.NOON_SALAH = {
 "steps": [
  {
   "id": "intro",
   "ar": "صلّوا كما رأيتموني أصلّي",
   "en": "Pray as you have seen me pray",
   "hadith": [
    {
     "ar": "وَصَلُّوا كَمَا رَأَيْتُمُونِي أُصَلِّي",
     "en": "Pray as you have seen me praying",
     "refAr": "صحيح البخاري ٦٣١",
     "refEn": "Sahih al-Bukhari 631"
    }
   ]
  },
  {
   "id": "niyyah",
   "ar": "النية",
   "en": "The intention",
   "hadith": [
    {
     "ar": "إِنَّمَا الْأَعْمَالُ بِالنِّيَّاتِ، وَإِنَّمَا لِكُلِّ امْرِئٍ مَا نَوَى",
     "en": "The reward of deeds depends upon the intentions and every person will get the reward according to what he has intended",
     "refAr": "صحيح البخاري ١",
     "refEn": "Sahih al-Bukhari 1"
    }
   ]
  },
  {
   "id": "qibla",
   "ar": "استقبال القبلة وتكبيرة الإحرام",
   "en": "Facing the qibla and the opening takbir",
   "hadith": [
    {
     "ar": "إِذَا قُمْتَ إِلَى الصَّلاَةِ فَأَسْبِغِ الْوُضُوءَ، ثُمَّ اسْتَقْبِلِ الْقِبْلَةَ فَكَبِّرْ",
     "en": "When you stand for prayer, perform ablution properly and then face the Qibla and say Takbir (Allahu-Akbar)",
     "refAr": "صحيح البخاري ٦٢٥١",
     "refEn": "Sahih al-Bukhari 6251"
    }
   ]
  },
  {
   "id": "hands",
   "ar": "رفع اليدين",
   "en": "Raising the hands",
   "hadith": [
    {
     "ar": "كَانَ يَرْفَعُ يَدَيْهِ حَذْوَ مَنْكِبَيْهِ إِذَا افْتَتَحَ الصَّلاَةَ، وَإِذَا كَبَّرَ لِلرُّكُوعِ، وَإِذَا رَفَعَ رَأْسَهُ مِنَ الرُّكُوعِ رَفَعَهُمَا كَذَلِكَ أَيْضًا وَقَالَ سَمِعَ اللَّهُ لِمَنْ حَمِدَهُ، رَبَّنَا وَلَكَ الْحَمْدُ . وَكَانَ لاَ يَفْعَلُ ذَلِكَ فِي السُّجُودِ",
     "en": "used to raise both his hands up to the level of his shoulders when opening the prayer; and on saying the Takbir for bowing. And on raising his head from bowing he used to do the same and then say \"Sami`a l-lahu liman hamidah, Rabbana wa laka l-hamd.\" And he did not do that (i.e. raising his hands) in prostrations",
     "refAr": "صحيح البخاري ٧٣٥",
     "refEn": "Sahih al-Bukhari 735"
    }
   ]
  },
  {
   "id": "right",
   "ar": "وضع اليد اليمنى على اليسرى",
   "en": "The right hand over the left",
   "hadith": [
    {
     "ar": "كَانَ النَّاسُ يُؤْمَرُونَ أَنْ يَضَعَ الرَّجُلُ الْيَدَ الْيُمْنَى عَلَى ذِرَاعِهِ الْيُسْرَى فِي الصَّلاَةِ",
     "en": "The people were ordered to place the right hand on the left forearm in the prayer",
     "refAr": "صحيح البخاري ٧٤٠",
     "refEn": "Sahih al-Bukhari 740"
    }
   ]
  },
  {
   "id": "istiftah",
   "ar": "دعاء الاستفتاح",
   "en": "The opening supplication",
   "hadith": [
    {
     "ar": "اللَّهُمَّ بَاعِدْ بَيْنِي وَبَيْنَ خَطَايَاىَ كَمَا بَاعَدْتَ بَيْنَ الْمَشْرِقِ وَالْمَغْرِبِ، اللَّهُمَّ نَقِّنِي مِنَ الْخَطَايَا كَمَا يُنَقَّى الثَّوْبُ الأَبْيَضُ مِنَ الدَّنَسِ، اللَّهُمَّ اغْسِلْ خَطَايَاىَ بِالْمَاءِ وَالثَّلْجِ وَالْبَرَدِ",
     "en": "Allahumma, baa`id baini wa baina khatayaya kama baa`adta baina l-mashriqi wa l-maghrib. Allahumma, naqqini min khatayaya kama yunaqqa th-thawbu l-abyadu mina d-danas. Allahumma, ighsil khatayaya bi l-maa'i wa th-thalji wa l-barad (O Allah! Set me apart from my sins (faults) as the East and West are set apart from each other and clean me from sins as a white garment is cleaned of dirt (after thorough washing). O Allah! Wash off my sins with water, snow and hail",
     "refAr": "صحيح البخاري ٧٤٤",
     "refEn": "Sahih al-Bukhari 744"
    }
   ]
  },
  {
   "id": "fatiha",
   "ar": "قراءة الفاتحة",
   "en": "Reciting al-Fatiha",
   "hadith": [
    {
     "ar": "لاَ صَلاَةَ لِمَنْ لَمْ يَقْرَأْ بِفَاتِحَةِ الْكِتَابِ",
     "en": "Whoever does not recite Al-Fatiha in his prayer, his prayer is invalid",
     "refAr": "صحيح البخاري ٧٥٦",
     "refEn": "Sahih al-Bukhari 756"
    }
   ]
  },
  {
   "id": "amin",
   "ar": "التأمين",
   "en": "Saying Amin",
   "hadith": [
    {
     "ar": "إِذَا أَمَّنَ الإِمَامُ فَأَمِّنُوا فَإِنَّهُ مَنْ وَافَقَ تَأْمِينُهُ تَأْمِينَ الْمَلاَئِكَةِ غُفِرَ لَهُ مَا تَقَدَّمَ مِنْ ذَنْبِهِ",
     "en": "Say Amin\" when the Imam says it and if the Amin of any one of you coincides with that of the angels then all his past sins will be forgiven",
     "refAr": "صحيح البخاري ٧٨٠",
     "refEn": "Sahih al-Bukhari 780"
    }
   ]
  },
  {
   "id": "ruku",
   "ar": "الركوع والاعتدال منه بطمأنينة",
   "en": "Bowing and rising from it, calmly",
   "hadith": [
    {
     "ar": "ثُمَّ ارْكَعْ حَتَّى تَطْمَئِنَّ رَاكِعًا، ثُمَّ ارْفَعْ حَتَّى تَعْتَدِلَ قَائِمًا",
     "en": "then bow till you feel at ease. Then raise your head and stand up straight",
     "refAr": "صحيح البخاري ٧٥٧",
     "refEn": "Sahih al-Bukhari 757"
    }
   ]
  },
  {
   "id": "rukuDhikr",
   "ar": "ما يقال في الركوع والرفع منه",
   "en": "What is said in bowing and on rising",
   "hadith": [
    {
     "ar": "ثُمَّ رَكَعَ فَجَعَلَ يَقُولُ سُبْحَانَ رَبِّيَ الْعَظِيمِ",
     "en": "would then bow and say: Glory be to my Mighty Lord",
     "refAr": "صحيح مسلم ٧٧٢",
     "refEn": "Sahih Muslim 772"
    },
    {
     "ar": "ثُمَّ يَقُولُ سَمِعَ اللَّهُ لَمِنْ حَمِدَهُ. حِينَ يَرْفَعُ صُلْبَهُ مِنَ الرَّكْعَةِ، ثُمَّ يَقُولُ وَهُوَ قَائِمٌ رَبَّنَا لَكَ الْحَمْدُ",
     "en": "On rising from bowing he said, \"Sami`a llahu liman hamidah,\" and then while standing straight he used to say, \"Rabbana laka-l hamd",
     "refAr": "صحيح البخاري ٧٨٩",
     "refEn": "Sahih al-Bukhari 789"
    }
   ]
  },
  {
   "id": "sujud",
   "ar": "السجود على الأعضاء السبعة",
   "en": "Prostrating on the seven bones",
   "hadith": [
    {
     "ar": "أُمِرْتُ أَنْ أَسْجُدَ عَلَى سَبْعَةِ أَعْظُمٍ عَلَى الْجَبْهَةِ ـ وَأَشَارَ بِيَدِهِ عَلَى أَنْفِهِ ـ وَالْيَدَيْنِ، وَالرُّكْبَتَيْنِ وَأَطْرَافِ الْقَدَمَيْنِ",
     "en": "I have been ordered to prostrate on seven bones i.e. on the forehead along with the tip of the nose and the Prophet (ﷺ) pointed towards his nose, both hands, both knees and the toes of both feet",
     "refAr": "صحيح البخاري ٨١٢",
     "refEn": "Sahih al-Bukhari 812"
    }
   ]
  },
  {
   "id": "sujudDhikr",
   "ar": "ما يقال في السجود",
   "en": "What is said in prostration",
   "hadith": [
    {
     "ar": "ثُمَّ سَجَدَ فَقَالَ سُبْحَانَ رَبِّيَ الأَعْلَى",
     "en": "He would then prostrate himself and say: Glory be to my Lord most High",
     "refAr": "صحيح مسلم ٧٧٢",
     "refEn": "Sahih Muslim 772"
    }
   ]
  },
  {
   "id": "jalsa",
   "ar": "الجلوس بين السجدتين",
   "en": "Sitting between the two prostrations",
   "hadith": [
    {
     "ar": "ثُمَّ اسْجُدْ حَتَّى تَطْمَئِنَّ سَاجِدًا، ثُمَّ ارْفَعْ حَتَّى تَطْمَئِنَّ جَالِسًا، وَافْعَلْ ذَلِكَ فِي صَلاَتِكَ كُلِّهَا",
     "en": "then prostrate till you feel at ease during your prostration, then sit with calmness till you feel at ease (do not hurry) and do the same in all your prayers",
     "refAr": "صحيح البخاري ٧٥٧",
     "refEn": "Sahih al-Bukhari 757"
    },
    {
     "ar": "وَكَانَ يَقُولُ رَبِّ اغْفِرْ لِي رَبِّ اغْفِرْ لِي",
     "en": "and said while sitting: \"O my Lord forgive me",
     "refAr": "سنن أبي داود ٨٧٤، صحّحه الألباني",
     "refEn": "Sunan Abi Dawud 874, graded sahih by al-Albani"
    }
   ]
  },
  {
   "id": "tashahhud",
   "ar": "التشهد",
   "en": "The tashahhud",
   "hadith": [
    {
     "ar": "فَلْيَقُلِ التَّحِيَّاتُ لِلَّهِ، وَالصَّلَوَاتُ وَالطَّيِّبَاتُ، السَّلاَمُ عَلَيْكَ أَيُّهَا النَّبِيُّ وَرَحْمَةُ اللَّهِ وَبَرَكَاتُهُ، السَّلاَمُ عَلَيْنَا وَعَلَى عِبَادِ اللَّهِ الصَّالِحِينَ. فَإِنَّكُمْ إِذَا قُلْتُمُوهَا أَصَابَتْ كُلَّ عَبْدٍ لِلَّهِ صَالِحٍ فِي السَّمَاءِ وَالأَرْضِ، أَشْهَدُ أَنْ لاَ إِلَهَ إِلاَّ اللَّهُ، وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ",
     "en": "he should say, at-Tahiyatu li l-lahi wa ssalawatu wa t-taiyibat. As-salamu `alalika aiyuha n-Nabiyu wa rahmatu l-lahi wa barakatuh. Assalamu `alaina wa `ala `ibadi l-lahi s-salihin. (All the compliments, prayers and good things are due to Allah; peace be on you, O Prophet, and Allah's mercy and blessings [be on you]. Peace be on us an on the pious subjects of Allah). (If you say that, it will reach all the subjects in the heaven and the earth). Ash-hadu al-la ilaha illa l-lah, wa ash-hadu anna Muhammadan `Abduhu wa Rasuluh",
     "refAr": "صحيح البخاري ٨٣١",
     "refEn": "Sahih al-Bukhari 831"
    }
   ]
  },
  {
   "id": "salawat",
   "ar": "الصلاة على النبي ﷺ",
   "en": "Blessings on the Prophet ﷺ",
   "hadith": [
    {
     "ar": "قُولُوا اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ، وَعَلَى آلِ مُحَمَّدٍ، كَمَا صَلَّيْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ، إِنَّكَ حَمِيدٌ مَجِيدٌ، اللَّهُمَّ بَارِكْ عَلَى مُحَمَّدٍ، وَعَلَى آلِ مُحَمَّدٍ، كَمَا بَارَكْتَ عَلَى إِبْرَاهِيمَ، وَعَلَى آلِ إِبْرَاهِيمَ، إِنَّكَ حَمِيدٌ مَجِيدٌ",
     "en": "Say: O Allah! Send Your Mercy on Muhammad and on the family of Muhammad, as You sent Your Mercy on Abraham and on the family of Abraham, for You are the Most Praise-worthy, the Most Glorious. O Allah! Send Your Blessings on Muhammad and the family of Muhammad, as You sent your Blessings on Abraham and on the family of Abraham, for You are the Most Praise-worthy, the Most Glorious",
     "refAr": "صحيح البخاري ٣٣٧٠",
     "refEn": "Sahih al-Bukhari 3370"
    }
   ]
  },
  {
   "id": "taawwudh",
   "ar": "الاستعاذة من أربع قبل السلام",
   "en": "Seeking refuge from four things before the salam",
   "hadith": [
    {
     "ar": "إِذَا فَرَغَ أَحَدُكُمْ مِنَ التَّشَهُّدِ الآخِرِ فَلْيَتَعَوَّذْ بِاللَّهِ مِنْ أَرْبَعٍ مِنْ عَذَابِ جَهَنَّمَ وَمِنْ عَذَابِ الْقَبْرِ وَمِنْ فِتْنَةِ الْمَحْيَا وَالْمَمَاتِ وَمِنْ شَرِّ الْمَسِيحِ الدَّجَّالِ",
     "en": "When any one of you completes the last tashahhud. he should seek refuge with Allah from four (trials). I.e. from the torment of Hell, from the torment of grave, from the trial of life and death, and from the mischief of Masih at-Dajjal (Antichrist)",
     "refAr": "صحيح مسلم ٥٨٨",
     "refEn": "Sahih Muslim 588"
    }
   ]
  },
  {
   "id": "taslim",
   "ar": "التسليم",
   "en": "The closing salam",
   "hadith": [
    {
     "ar": "يُسَلِّمُ عَنْ يَمِينِهِ وَعَنْ يَسَارِهِ حَتَّى أَرَى بَيَاضَ خَدِّهِ",
     "en": "pronouncing taslim on his right and on his left till I saw the whiteness of his cheek",
     "refAr": "صحيح مسلم ٥٨٢",
     "refEn": "Sahih Muslim 582"
    }
   ]
  }
 ],
 "book": {
  "ar": "صفة صلاة النبي ﷺ من التكبير إلى التسليم كأنك تراها — الشيخ محمد ناصر الدين الألباني",
  "en": "The Prophet’s Prayer Described — Shaykh Muhammad Nasir ad-Din al-Albani",
  "url": "https://shamela.ws/book/657",
  "full": "https://shamela.ws/book/9875"
 }
};
