// Generated by tools/build_sunnah.py from the hadith collections and the Mushaf data. Do not edit by hand.
window.NOON_SUNNAH_TEXTS = {
 "monThu": {
  "ar": "تُعْرَضُ الأَعْمَالُ يَوْمَ الاِثْنَيْنِ وَالْخَمِيسِ فَأُحِبُّ أَنْ يُعْرَضَ عَمَلِي وَأَنَا صَائِمٌ",
  "en": "Deeds are presented on Monday and Thursday, and I love that my deeds be presented while I am fasting",
  "refAr": "سنن الترمذي ٧٤٧، صحّحه الألباني",
  "refEn": "Jami' at-Tirmidhi 747, graded sahih by al-Albani"
 },
 "monday": {
  "ar": "سُئِلَ عَنْ صَوْمِ الاِثْنَيْنِ فَقَالَ فِيهِ وُلِدْتُ وَفِيهِ أُنْزِلَ عَلَىَّ",
  "en": "was asked about fasting on Monday, whereupon he said:It is (the day) when I was born and revelation was sent down to me",
  "refAr": "صحيح مسلم ١١٦٢",
  "refEn": "Sahih Muslim 1162"
 },
 "white": {
  "ar": "إِذَا صُمْتَ مِنَ الشَّهْرِ ثَلاَثَةَ أَيَّامٍ فَصُمْ ثَلاَثَ عَشْرَةَ وَأَرْبَعَ عَشْرَةَ وَخَمْسَ عَشْرَةَ",
  "en": "When you fast three days out of a month, then fast the thirteenth, fourteenth, and fifteenth",
  "refAr": "سنن الترمذي ٧٦١، قال الألباني: حسن صحيح",
  "refEn": "Jami' at-Tirmidhi 761, graded hasan sahih by al-Albani"
 },
 "arafah": {
  "ar": "صِيَامُ يَوْمِ عَرَفَةَ أَحْتَسِبُ عَلَى اللَّهِ أَنْ يُكَفِّرَ السَّنَةَ الَّتِي قَبْلَهُ وَالسَّنَةَ الَّتِي بَعْدَهُ",
  "en": "fasting on the day of 'Arafa may atone for the sins of the preceding and the coming years",
  "refAr": "صحيح مسلم ١١٦٢",
  "refEn": "Sahih Muslim 1162"
 },
 "ashura": {
  "ar": "وَصِيَامُ يَوْمِ عَاشُورَاءَ أَحْتَسِبُ عَلَى اللَّهِ أَنْ يُكَفِّرَ السَّنَةَ الَّتِي قَبْلَهُ",
  "en": "fasting on the day of Ashura may atone for the sins of the preceding year",
  "refAr": "صحيح مسلم ١١٦٢",
  "refEn": "Sahih Muslim 1162"
 },
 "tasua": {
  "ar": "لَئِنْ بَقِيتُ إِلَى قَابِلٍ لأَصُومَنَّ التَّاسِعَ",
  "en": "If I live till the next (year), I would definitely observe fast on the 9th",
  "refAr": "صحيح مسلم ١١٣٤",
  "refEn": "Sahih Muslim 1134"
 },
 "shawwal": {
  "ar": "مَنْ صَامَ رَمَضَانَ ثُمَّ أَتْبَعَهُ سِتًّا مِنْ شَوَّالٍ كَانَ كَصِيَامِ الدَّهْرِ",
  "en": "He who observed the fast of Ramadan and then followed it with six (fasts) of Shawwal. it would be as if he fasted perpetually",
  "refAr": "صحيح مسلم ١١٦٤",
  "refEn": "Sahih Muslim 1164"
 },
 "dhulhijja": {
  "ar": "مَا الْعَمَلُ فِي أَيَّامِ الْعَشْرِ أَفْضَلَ مِنَ الْعَمَلِ فِي هَذِهِ",
  "en": "No good deeds done on other days are superior to those done on these (first ten days of Dhul Hijja)",
  "refAr": "صحيح البخاري ٩٦٩",
  "refEn": "Sahih al-Bukhari 969"
 },
 "muharram": {
  "ar": "أَفْضَلُ الصِّيَامِ بَعْدَ رَمَضَانَ شَهْرُ اللَّهِ الْمُحَرَّمُ",
  "en": "The most excellent fast after Ramadan is God's month. al-Muharram",
  "refAr": "صحيح مسلم ١١٦٣",
  "refEn": "Sahih Muslim 1163"
 },
 "shaban": {
  "ar": "فَمَا رَأَيْتُ رَسُولَ اللَّهِ صلى الله عليه وسلم اسْتَكْمَلَ صِيَامَ شَهْرٍ إِلاَّ رَمَضَانَ، وَمَا رَأَيْتُهُ أَكْثَرَ صِيَامًا مِنْهُ فِي شَعْبَانَ",
  "en": "I never saw Allah's Messenger (ﷺ) fasting for a whole month except the month of Ramadan, and did not see him fasting in any month more than in the month of Sha'ban",
  "refAr": "صحيح البخاري ١٩٦٩",
  "refEn": "Sahih al-Bukhari 1969"
 },
 "ramadan": {
  "ar": "مَنْ صَامَ رَمَضَانَ إِيمَانًا وَاحْتِسَابًا غُفِرَ لَهُ مَا تَقَدَّمَ مِنْ ذَنْبِهِ",
  "en": "Whoever observes fasts during the month of Ramadan out of sincere faith, and hoping to attain Allah's rewards, then all his past sins will be forgiven",
  "refAr": "صحيح البخاري ٣٨",
  "refEn": "Sahih al-Bukhari 38"
 },
 "lastTen": {
  "ar": "تَحَرَّوْا لَيْلَةَ الْقَدْرِ فِي الْوِتْرِ مِنَ الْعَشْرِ الأَوَاخِرِ مِنْ رَمَضَانَ",
  "en": "Search for the Night of Qadr in the odd nights of the last ten days of Ramadan",
  "refAr": "صحيح البخاري ٢٠١٧",
  "refEn": "Sahih al-Bukhari 2017"
 },
 "eid": {
  "ar": "نَهَى النَّبِيُّ صلى الله عليه وسلم عَنْ صَوْمِ يَوْمِ الْفِطْرِ وَالنَّحْرِ",
  "en": "The Prophet (ﷺ) forbade the fasting of `Id-ul-Fitr and `Id-ul-Adha (two feast days)",
  "refAr": "صحيح البخاري ١٩٩١",
  "refEn": "Sahih al-Bukhari 1991"
 },
 "tashreeq": {
  "ar": "أَيَّامُ التَّشْرِيقِ أَيَّامُ أَكْلٍ وَشُرْبٍ",
  "en": "The days of Tashriq are the days of eating and drinking",
  "refAr": "صحيح مسلم ١١٤١",
  "refEn": "Sahih Muslim 1141"
 },
 "friday": {
  "ar": "إِنَّ مِنْ أَفْضَلِ أَيَّامِكُمْ يَوْمَ الْجُمُعَةِ فِيهِ خُلِقَ آدَمُ وَفِيهِ قُبِضَ وَفِيهِ النَّفْخَةُ وَفِيهِ الصَّعْقَةُ فَأَكْثِرُوا عَلَىَّ مِنَ الصَّلاَةِ فِيهِ فَإِنَّ صَلاَتَكُمْ مَعْرُوضَةٌ عَلَىَّ",
  "en": "Among the most excellent of your days is Friday; on it Adam was created, on it he died, on it the last trumpet will be blown, and on it the shout will be made, so invoke more blessings on me that day, for your blessings will be submitted to me",
  "refAr": "سنن أبي داود ١٠٤٧، صحّحه الألباني",
  "refEn": "Sunan Abi Dawud 1047, graded sahih by al-Albani"
 },
 "fridayFast": {
  "ar": "لاَ يَصُومَنَّ أَحَدُكُمْ يَوْمَ الْجُمُعَةِ، إِلاَّ يَوْمًا قَبْلَهُ أَوْ بَعْدَهُ",
  "en": "None of you should fast on Friday unless he fasts a day before or after it",
  "refAr": "صحيح البخاري ١٩٨٥",
  "refEn": "Sahih al-Bukhari 1985"
 },
 "kahf": {
  "ar": "مَنْ قَرَأَ سُورَةَ الْكَهْفِ فِي يَوْمِ الْجُمُعَةِ أَضَاءَ لَهُ مِنَ النُّورِ مَا بَيْنَ الْجُمُعَتَيْنِ",
  "en": "Whoever recites Surat al-Kahf on Friday, light will shine for him between the two Fridays.",
  "refAr": "رواه الحاكم والبيهقي عن أبي سعيد الخدري، وصحّحه الألباني (صحيح الجامع ٦٤٧٠)",
  "refEn": "Al-Hakim and al-Bayhaqi, from Abu Sa'id al-Khudri; graded sahih by al-Albani (Sahih al-Jami' 6470)"
 },
 "adhkar": {
  "ar": "فَٱصْبِرْ عَلَىٰ مَا يَقُولُونَ وَسَبِّحْ بِحَمْدِ رَبِّكَ قَبْلَ طُلُوعِ ٱلشَّمْسِ وَقَبْلَ ٱلْغُرُوبِ",
  "en": "So be patient, [O Muhammad], over what they say and exalt [Allah] with praise of your Lord before the rising of the sun and before its setting,",
  "refAr": "سُورَةُ قٓ ٣٩",
  "refEn": "Quran 50:39",
  "verse": true
 }
};
