// ---------- Tajweed: the name and a short explanation of each rule marked in quran/tajweed.json ----------
// Written once by hand (it is teaching text, not Quran text) and reviewed before publishing.
// The codes are those of the quran-tajweed edition (api.alquran.cloud); the colours are in index.html (.tj-*).
// Order: the order the rules are listed under a verse.
(typeof window !== 'undefined' ? window : globalThis).NOON_TAJWEED_RULES = {
  f: { ar: 'إخفاء', en: 'Ikhfa (hiding)',
    defAr: 'نون ساكنة أو تنوين بعدها حرف من حروف الإخفاء الخمسة عشر: تُنطق بين الإظهار والإدغام مع غنّة بمقدار حركتين.',
    defEn: 'A silent noon or tanween before one of the fifteen ikhfa letters: said between clear and merged, with a nasal sound of two counts.' },
  c: { ar: 'إخفاء شفوي', en: 'Ikhfa shafawi (lip hiding)',
    defAr: 'ميم ساكنة بعدها باء: تُخفى الميم مع غنّة بمقدار حركتين.',
    defEn: 'A silent meem before a baa: the meem is hidden, with a nasal sound of two counts.' },
  i: { ar: 'إقلاب', en: 'Iqlab (turning)',
    defAr: 'نون ساكنة أو تنوين بعدها باء: تُقلب النون ميماً مخفاة مع غنّة بمقدار حركتين.',
    defEn: 'A silent noon or tanween before a baa: the noon turns into a hidden meem, with a nasal sound of two counts.' },
  a: { ar: 'إدغام بغنّة', en: 'Idgham with ghunnah',
    defAr: 'نون ساكنة أو تنوين في آخر كلمة، وأول الكلمة بعدها من حروف «ينمو»: تُدغم فيه مع غنّة.',
    defEn: 'A silent noon or tanween at the end of a word, with the next word starting with ya, noon, meem or waw: merged into it with a nasal sound.' },
  u: { ar: 'إدغام بلا غنّة', en: 'Idgham without ghunnah',
    defAr: 'نون ساكنة أو تنوين في آخر كلمة، وأول الكلمة بعدها لام أو راء: تُدغم فيها بلا غنّة.',
    defEn: 'A silent noon or tanween at the end of a word, with the next word starting with lam or ra: merged into it without a nasal sound.' },
  w: { ar: 'إدغام شفوي', en: 'Idgham shafawi (lip merging)',
    defAr: 'ميم ساكنة بعدها ميم: تُدغم الأولى في الثانية مع غنّة.',
    defEn: 'A silent meem before another meem: the first merges into the second, with a nasal sound.' },
  d: { ar: 'إدغام متجانسين', en: 'Idgham of kindred letters',
    defAr: 'حرفان من مخرج واحد، الأول ساكن: يُدغم في الثاني، كما في «قَد تَّبَيَّنَ».',
    defEn: 'Two letters from the same point of articulation, the first silent: it merges into the second.' },
  b: { ar: 'إدغام متقاربين', en: 'Idgham of close letters',
    defAr: 'حرفان متقاربان في المخرج، الأول ساكن: يُدغم في الثاني، كما في «أَلَمْ نَخْلُقكُّم».',
    defEn: 'Two letters close in articulation, the first silent: it merges into the second.' },
  g: { ar: 'غنّة', en: 'Ghunnah (nasal sound)',
    defAr: 'نون أو ميم مشدّدة: يخرج صوتها من الأنف بمقدار حركتين.',
    defEn: 'A doubled noon or meem: its sound comes through the nose for two counts.' },
  q: { ar: 'قلقلة', en: 'Qalqalah (echo)',
    defAr: 'أحد حروف «قطب جد» ساكناً: يُنطق بنبرة واضحة كأنه يرتدّ.',
    defEn: 'One of the letters qaf, ta, ba, jeem, dal when silent: said with a slight bouncing echo.' },
  n: { ar: 'مدّ طبيعي', en: 'Natural madd',
    defAr: 'حرف مدّ ليس بعده همز ولا سكون: يُمدّ حركتين.',
    defEn: 'A long vowel with no hamza or sukoon after it: held for two counts.' },
  o: { ar: 'مدّ واجب متصل', en: 'Obligatory madd',
    defAr: 'حرف مدّ بعده همزة في الكلمة نفسها: يُمدّ أربع أو خمس حركات.',
    defEn: 'A long vowel followed by a hamza in the same word: held for four or five counts.' },
  p: { ar: 'مدّ جائز', en: 'Permissible madd',
    defAr: 'مدّ يجوز فيه أكثر من مقدار، كالمدّ المنفصل (حرف مدّ آخر الكلمة وهمزة أول التي بعدها) والمدّ العارض للسكون عند الوقف.',
    defEn: 'A madd that may be held for more than one length, such as a long vowel before a hamza in the next word, or before a stop.' },
  m: { ar: 'مدّ لازم', en: 'Necessary madd',
    defAr: 'حرف مدّ بعده سكون ثابت، كما في «الضَّالِّينَ» وأوائل بعض السور: يُمدّ ست حركات.',
    defEn: 'A long vowel followed by a fixed sukoon, as in some letters opening surahs: held for six counts.' },
  l: { ar: 'لام شمسية', en: 'Sun letter lam',
    defAr: 'لام «ال» قبل حرف شمسي: تُكتب ولا تُنطق، ويُشدّد الحرف بعدها.',
    defEn: 'The lam of "al" before a sun letter: written but not said, and the next letter is doubled.' },
  h: { ar: 'همزة وصل', en: 'Hamzat al-wasl',
    defAr: 'همزة تُنطق إذا بدأت بها القراءة، وتسقط إذا وصلتها بما قبلها.',
    defEn: 'A hamza said when you start reading from it, and dropped when you join it to the word before.' },
  s: { ar: 'حرف لا يُنطق', en: 'Silent letter',
    defAr: 'حرف يُكتب في رسم المصحف ولا يُقرأ، كالألف في «قَالُوا».',
    defEn: 'A letter written in the Mushaf but not read, like the alif at the end of "qaalu".' }
};
